config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'letters#index'
  root 'records#index'
  resources :users
  resources :letters
  resources :records
  resources :records do
    collection { post :import }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/letter.rb
class Letter < ActiveRecord::Base
  belongs_to :user
  has_many :records

  def total_price
    # convert to array so it doesn't try to do sum on database directly
    records.to_a.sum(&:full_price)
  end
end

app/models/record.rb
class Record < ActiveRecord::Base
belongs_to :letter
belongs_to :user
#attr_accessible :name, :price, :released_on
validates :name, presence: true
validates :unit_value, presence: true
validates :template, presence: true
def full_price
    unit_value*quantity
end

def self.to_csv(options = {})
    CSV.generate(options) do |csv|
    csv << column_names
    all.each do |record|
        csv << record.attributes.values_at(*column_names)
    end
  end
end

def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
    Record.create! row.to_hash
    end
end

def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
end
end

=begin  does not work for some reason. 
code exact as the material show working.
def self.import(file)
spreadsheet = open_spreadsheet(file)
header = spreadsheet.row(1)
(2..spreadsheet.last_row).each do |i|
    row = Hash[[header, spreadsheet.row(i)].transpose]
    product = find_by_id(row["id"]) || new
    product.attributes = row.to_hash.slice(*accessible_attributes)
    product.save!
end
end
=end

app/models/user.rb
class User < ApplicationRecord
  has_many :letters
  has_many :records
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :email, presence: true
  validates :encrypted_password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
    def index
        @letters = Letter.all
    end
    

    def show
      @letter = Letter.find(params[:id])
      respond_to do |format|
        format.html
        format.xml {render:xml => @letters}
        format.pdf do
          pdf = Aip1.new(@letter, view_context)
          send_data pdf.render, filename: "Letter_#{@letter.letter_number}.pdf",
                                type: "application/pdf",
                                disposition: "inline"
                                #disposition: "attachment"
        end
      end
    end
    # def generate_all
    #     @letters = letter.order(:number)
    #     Letter.each do |r|
    #     pdf = LetterPdf1.new(r, view_context)
    #     FileUtils::copy_file("letter_#{@letter.letter_number}.pdf","./files")
    #     end
    # end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
    def index
      @records = Record.order(:name)
      respond_to do |format|
      format.html
      format.csv { send_data @records.to_csv }
      #format.xls
      end
    end

    def import
      Record.import(params[:file])
      redirect_to root_url, notice: "Records imported."
    end

    def show
      @record = Record.find(params[:id])
      respond_to do |format|
        format.html
        format.pdf do
          pdf = Aip1.new(@record, view_context)
          send_data pdf.render, filename: "letter_#{@letter.letter_id}.pdf",
                                type: "application/pdf",
                                disposition: "inline"
        end
      end
    end
    # def generate_all
    #   @records = Record.order(:name)
    #   Record.each do |r|
    #   pdf = LetterPdf1.new(r, view_context)
    #   FileUtils::copy_file("letter_#{@letter.letter_id}.pdf","./files")
    #   end
    # # ...
    # # temp_file_path = "./document/#{@report.report_name}.pdf"
    # # FileUtils::copy_file(rand_file,temp_file_path)
    # end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AIP Letters</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
<div id="container">  
      <nav >
        <a class="navbar-brand" href="#">AIP Letters</a>
<div>
<ul class="navbar-nav">
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
    </li>
  <% else %>
    <li class="nav-item">
      <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
    </li>
  <% end %>
</ul>
  </div>

        <div>
          <ul >
            <li>
              <%= link_to 'See All Letters', letters_path, class: 'nav-link' %> | <%= link_to 'See All Records', records_path, class: 'nav-link' %>
            </li>
          </ul>

        </div>
      </nav>
<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
</div>
    <div id="container">  
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/letters/index.html.erb
<h1>Letters</h1>
<ul>
<% @letters.each do |letter| %>
  <li><%= link_to "Letter \##{letter.letter_number}", letter %></li>

      <% if letter.user.present? %>
      <small><%= letter.user.email %></small>
    <% end %>
<% end %>
</ul>

app/views/letters/show.html.erb
<h1>Letter #<%= @letter.letter_number %></h1>

<table id="records">
  <tr>
    <th>AIP </th>
    <th>Qty</th>
    <th class="price">Unit Price</th>
    <th class="price">Full Price</th>
  </tr>
  <% @letter.records.each do |record| %>
    <tr class="<%= cycle :odd, :even %>">
      <td><%= record.name %></td>
      <td class="qty"><%= record.quantity %></td>
      <td class="price"><%= number_to_currency(record.unit_price) %></td>
      <td class="price"><%= number_to_currency(record.full_price) %></td>
    </tr>
  <% end %>
  <tr>
    <td class="total price" colspan="4">
      Total: <%= number_to_currency @letter.total_price %>
    </td>
  </tr>
</table>

<p><%= link_to "Printable Letter (PDF)", letter_path(@letter, format: "pdf") %></p>

app/views/records/index.html.erb
<p>
  Download:
  <%= link_to "CSV", records_path(format: "csv") %> |
  <%= link_to "Excel", records_path(format: "xls") %>|

</p>
<h2>Import Records</h2>
<p>

<table><th>Steps:</th>
<td>1. Prepare CSV file with records.</td>
<td>2. Click "Choose File".</td>
<td>3. Click "Import"</td>
</table>
</p>
<p>
<%= form_tag import_records_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
</p>
<h1>Records</h1>
<table id="records">
  <tr>
    <th>name</th>
    <th>unit_value</th>
    <th>quantity</th>
    <th>template</th>
  
  </tr>
<% @records.each do |record| %>
  <tr>
    <td><%= record.name %></td>
    <td><%= record.unit_value %></td>
    <td><%= record.quantity %></td>
    <td><%= record.template %></td>
  </tr>
<% end %>
</table>

app/views/records/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="Integer">letter_id</Data></Cell>
        <Cell><Data ss:Type="String">name</Data></Cell>
        <Cell><Data ss:Type="Decimal">unit_value</Data></Cell>
        <Cell><Data ss:Type="integer">quantity</Data></Cell>
        <Cell><Data ss:Type="integer">template</Data></Cell>

      </Row>
    <% @records.each do |record| %>
      <Row>
        <Cell><Data ss:Type="Integer"><%= record.letter_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= record.name %></Data></Cell>
        <Cell><Data ss:Type="Decimal"><%= record.unit_value %></Data></Cell>
        <Cell><Data ss:Type="Integer"><%= record.quantity %></Data></Cell>
        <Cell><Data ss:Type="Integer"><%= record.template %></Data></Cell>

      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/records/show.html.erb
<h1>Record #<%= @record.id %></h1>

<table id="records">
  <tr>
    <th>AIP </th>
    <th>Qty</th>
    <th class="price">Unit Price</th>
    <th class="price">Full Price</th>
  </tr>
  <% @letter.records.each do |record| %>
    <tr class="<%= cycle :odd, :even %>">
      <td><%= record.name %></td>
      <td class="qty"><%= record.quantity %></td>
      <td class="price"><%= number_to_currency(record.unit_value) %></td>
      <td class="price"><%= number_to_currency(record.full_price) %></td>
    </tr>
  <% end %>
  <tr>
    <td class="total price" colspan="4">
      Total: <%= number_to_currency @letter.total_price %>
    </td>
  </tr>
</table>